### PR TITLE
fix disposing of controller

### PR DESCRIPTION
**Pull request by gigi214**
This is my first pull request and contribution to a public repository. I'm also pretty new on Flutter.
I added a bool variable in order to avoid the disposing of the controller when it's passed by parameter.
Fixing in this way the issue #14

### CODE REVIEW

**Review by leo-paz — APPROVED** [review]

**Comment by leo-paz** [comment]
@apgapg @federicodesia any chance this can be merged?

I think the point of the controller should be to control the timer from within other parts of the app (eg. store it in global state so that you can trigger the timer from somewhere else in your app)

**Comment by federicodesia** [comment]
Sorry for the inactivity, I haven't been able to maintain the project during this time.
Thank you very much for contributing and helping to improve this package! 🚀
I will update the changes in a new version and it will be available on pub.dev soon.

**Comment by leo-paz** [comment]
@federicodesia No worries. Thanks for doing that.

I was wondering if you had any ideas on what the best way to have the controller be able to tell you what time the timer is at so you can do some logic with it in other parts of the app?

Right now it seems like the animation controller is what knows the current value of time which if the view is disposed of, you'll lose track of. You could update the controller when the animation controller updates but that doesn't seem clean as in my opinion the controller should be source of truth. 

If you have any ideas i'd be happy to contribute as I need this for my own work

**Comment by federicodesia** [comment]
Yes, I think the same. The current value should be view agnostic.

The first version of the package before it was released worked the way you mention. But this caused a lot of bugs and view update delays, especially when using milliseconds or microseconds. Using the animated widget fixes those issues, even on older devices.

I think you're looking for behavior similar to #12.

It occurs to me that we could tell the animation controller the current value.
I'll try to update it when I have some free time, but if you have another idea let me know.

**Comment by leo-paz** [comment]
Yes similar but in my case it will be a constant timer that continuously resets (restore a users heart when they lose hearts in my game).

I was thinking of using `Timer` from `dart:async` in the controller. Similar to [this example](https://www.flutterbeads.com/flutter-countdown-timer/#:~:text=Steps%20to%20add%20countdown%20timer,()%20to%20stop%20the%20timer.)

And have the widget itself access the duration field that is changing?

**Comment by federicodesia** [comment]
If you want you can create a new issue by adding a minimal reproduction sample detailing the expected behavior, to follow it there. I think I would not modify this package to use `Timer` again to fix the specific use case.

**Comment by leo-paz** [comment]
Created an issue. Would be great if you put down your thoughts on why `Timer` didn't work and what you're thinking of doing

**Pull request merged**
